import 'package:washly/utils/models/car.dart';
import 'package:washly/utils/models/order.dart';

List<Order> orders = [
  Order(
      clientFullName: "Abdessamad Berahhou",
      distance: 10,
      clientAvatar: "assets/images/profile.png",
      orderStatus: 1,
      orderType: "standard",
      orderCar: Car(
          carColor: "red",
          carPicture: "assets/images/car.png",
          carMark: "Mercedes",
          carMatricule: "16953 - B - 5",
          carModel: 2019,
          carName: "Merceded G63",
          carType: "Big"),
      orderAddress: "Rue de far 12, Casablanca, Morocco",
      orderDiscount: 19,
      orderPaymentMethod: 0,
      orderSubtotal: 90),
  Order(
      clientFullName: "Abdessamad Berahhou1",
      distance: 15,
      clientAvatar: "assets/images/profile.png",
      orderStatus: 1,
      orderType: "standard",
      orderCar: Car(
          carColor: "red",
          carMark: "Volvo",
          carPicture: "assets/images/car.png",
          carMatricule: "16793 - C - 5",
          carModel: 2020,
          carName: "Volvo a80",
          carType: "Big"),
      orderAddress: "Rue de far 13, Casablanca, Morocco",
      orderDiscount: 0,
      orderPaymentMethod: 1,
      orderSubtotal: 70),
  Order(
      clientFullName: "Abdessamad Berahhou2",
      distance: 22,
      clientAvatar: "assets/images/profile.png",
      orderStatus: 0,
      orderType: "standard",
      orderCar: Car(
          carColor: "red",
          carMark: "Mercedes",
          carPicture: "assets/images/car.png",
          carMatricule: "16953 - B - 5",
          carModel: 2019,
          carName: "Merceded G63",
          carType: "Big"),
      orderAddress: "Rue de far 14, Casablanca, Morocco",
      orderDiscount: 10,
      orderPaymentMethod: 1,
      orderSubtotal: 110),
  Order(
      clientFullName: "Abdessamad Berahhou3",
      distance: 19,
      clientAvatar: "assets/images/profile.png",
      orderStatus: 2,
      orderType: "standard",
      orderCar: Car(
          carColor: "red",
          carMark: "Volvo",
          carMatricule: "16793 - C - 5",
          carModel: 2020,
          carPicture: "assets/images/car.png",
          carName: "Volvo a80",
          carType: "Big"),
      orderAddress: "Rue de far 15, Casablanca, Morocco",
      orderDiscount: 40,
      orderPaymentMethod: 1,
      orderSubtotal: 80),
  Order(
      clientFullName: "Abdessamad Berahhou4",
      distance: 8,
      clientAvatar: "assets/images/profile.png",
      orderStatus: 1,
      orderType: "standard",
      orderCar: Car(
          carColor: "red",
          carMark: "Volvo",
          carMatricule: "16793 - C - 5",
          carModel: 2020,
          carName: "Volvo a80",
          carPicture: "assets/images/car.png",
          carType: "Big"),
      orderAddress: "Rue de far 16, Casablanca, Morocco",
      orderDiscount: 0,
      orderPaymentMethod: 0,
      orderSubtotal: 190),
];
